[package]
name = "statix"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../lib" }
ariadne = "0.1.3"
rnix = "0.9.0"
clap = "3.0.0-beta.4"
globset = "0.4.8"
thiserror = "1.0.30"
vfs = { path = "../vfs" }
